# Generated by Django 5.0.6 on 2024-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(default='yor address/location', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='your city', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='if you have one', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='county', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
